/**
 * Generating a deploy key.
 *
 * The operator-facing half of SSH authentication: consuming a key is `ssh-key.ts`, and this is where
 * one comes from. It exists because the alternative onboarding path was "run ssh-keygen by hand,
 * then edit secrets.json in nano", and a first-run procedure that involves hand-editing the file
 * that holds every project's credentials is a procedure that will eventually corrupt it.
 *
 * `ssh-keygen` rather than `node:crypto`. Node can generate an ED25519 pair, but it emits PKCS#8 and
 * SPKI, while GitHub needs the `ssh-ed25519 AAAA…` authorized-keys form and OpenSSH needs its own
 * private-key format. Hand-rolling SSH wire encoding to avoid a binary the image already installs
 * for the transport itself is a bad trade.
 *
 * ED25519 rather than RSA: shorter, faster, no key-size decision to get wrong, and supported by
 * every git host that matters. GitHub has accepted it for deploy keys for years.
 *
 * **The private key is returned in memory and never printed.** The caller stores it through
 * `secret-file-writer.ts` and prints only the public half.
 */

import { chmodSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { type Result, DeploymentError, err, ok } from "@/core/shared";

import type { CommandRunner } from "../command-runner";
import { authBaseDirectory, looksLikePrivateKey } from "./ssh-key";

const DIR_MODE = 0o700;
const KEY_MODE = 0o600;
const KEYGEN_TIMEOUT_MILLIS = 30_000;

export interface DeployKeyPair {
  /** OpenSSH private key. Store it; never print it. */
  readonly privateKey: string;
  /** `ssh-ed25519 AAAA… comment` — the line to paste into GitHub's Deploy keys screen. */
  readonly publicKey: string;
}

/**
 * Generate a keypair, reading both halves back before the temp directory is removed.
 *
 * The directory is created under the same base as the transport's session directories, so the boot
 * sweep covers a key generated by a command that was interrupted with exactly the same rules — one
 * place to reason about, one place that can be got wrong.
 */
export async function generateDeployKey(
  runner: CommandRunner,
  comment: string,
  base: string = tmpdir(),
): Promise<Result<DeployKeyPair>> {
  const directory = makeDirectory(base);
  if (!directory.ok) {
    return directory;
  }

  try {
    const keyPath = join(directory.value, "id_ed25519");

    // -N "" is an unencrypted key, deliberately: the worker has to use it unattended, so a
    // passphrase would have to be stored beside it and would protect nothing. The protection is the
    // 0600 secret store and the fact that the key is repository-scoped and read-only.
    const generated = await runner.run({
      command: "ssh-keygen",
      args: ["-t", "ed25519", "-N", "", "-C", comment, "-f", keyPath, "-q"],
      timeoutMillis: KEYGEN_TIMEOUT_MILLIS,
    });
    if (!generated.ok) {
      return generated;
    }
    if (generated.value.exitCode !== 0) {
      return err(keygenFailed(generated.value.stderr || generated.value.stdout));
    }

    const privateKey = readFileSync(keyPath, "utf8");
    const publicKey = readFileSync(`${keyPath}.pub`, "utf8").trim();

    if (!looksLikePrivateKey(privateKey) || !publicKey.startsWith("ssh-ed25519 ")) {
      // Cannot happen with a working ssh-keygen, and worth refusing rather than storing something
      // unusable that only fails at the first deployment.
      return err(keygenFailed("ssh-keygen produced output in an unexpected format"));
    }

    return ok({ privateKey, publicKey });
  } catch (cause) {
    return err(keygenFailed(messageOf(cause)));
  } finally {
    rmSync(directory.value, { recursive: true, force: true });
  }
}

/**
 * Re-derive the public half from a stored private key.
 *
 * So that losing the printed public key never means rotating a working deploy key. `ssh-keygen -y`
 * needs the key as a file, which is why this borrows the same temp-directory discipline; the private
 * key is written, read by ssh-keygen, and removed, and only the public half is ever returned.
 */
export async function derivePublicKey(
  runner: CommandRunner,
  privateKey: string,
  comment: string,
  base: string = tmpdir(),
): Promise<Result<string>> {
  if (!looksLikePrivateKey(privateKey)) {
    return err(
      DeploymentError.of(
        "PREFLIGHT_CREDENTIAL_MISSING",
        "That secret entry does not hold an SSH private key, so there is no public key to derive.",
        { details: {} },
      ),
    );
  }

  const directory = makeDirectory(base);
  if (!directory.ok) {
    return directory;
  }

  try {
    const keyPath = join(directory.value, "id_ed25519");
    writeFileSync(keyPath, privateKey.endsWith("\n") ? privateKey : `${privateKey}\n`, {
      mode: KEY_MODE,
    });
    chmodSync(keyPath, KEY_MODE);

    const derived = await runner.run({
      command: "ssh-keygen",
      args: ["-y", "-f", keyPath],
      timeoutMillis: KEYGEN_TIMEOUT_MILLIS,
    });
    if (!derived.ok) {
      return derived;
    }
    if (derived.value.exitCode !== 0) {
      // stderr from `ssh-keygen -y` reports the format problem and never echoes key material.
      return err(keygenFailed(derived.value.stderr || "ssh-keygen could not read the key"));
    }

    // An OpenSSH private key stores its own comment, so `-y` may print one already. Keeping only the
    // type and the key body and re-appending the comment gives one comment either way — appending
    // unconditionally produced `… deployhub:ref deployhub:ref`, which a test caught.
    const [type, body] = derived.value.stdout.trim().split(/\s+/);
    if (type === undefined || body === undefined) {
      return err(keygenFailed("ssh-keygen produced output in an unexpected format"));
    }
    return ok(`${type} ${body} ${comment}`);
  } catch (cause) {
    return err(keygenFailed(messageOf(cause)));
  } finally {
    rmSync(directory.value, { recursive: true, force: true });
  }
}

function makeDirectory(base: string): Result<string> {
  try {
    const root = authBaseDirectory(base);
    mkdirSync(root, { recursive: true, mode: DIR_MODE });
    chmodSync(root, DIR_MODE);
    const directory = mkdtempSync(join(root, `session-${process.pid}-`));
    chmodSync(directory, DIR_MODE);
    return ok(directory);
  } catch (cause) {
    return err(
      DeploymentError.of(
        "SECRET_STORE_UNAVAILABLE",
        `Cannot create a private directory for key generation: ${messageOf(cause)}`,
        { details: {} },
      ),
    );
  }
}

function keygenFailed(detail: string): DeploymentError {
  return DeploymentError.of("COMMAND_FAILED", `ssh-keygen failed: ${detail.trim()}`, {
    details: {},
  });
}

function messageOf(cause: unknown): string {
  return cause instanceof Error ? cause.message : String(cause);
}
